### ISSUE TITLE
Older Android support?

### ISSUE THREAD

**Issue by zekooooo** [dubrowgn/micro-timer#8]
Hello, found your app on F-Droid and it looks really simple and very useful, but unfortunately I can't install it because my phone has Android 7.0

Is there a feature stopping it from working on Android versions below 9.0? To me, it seems like the sort of thing that might work even on the most ancient Androids :)

**Comment by dubrowgn** [comment]
Thanks for your interest. I did actually look at this before, but unfortunately the API I use for the core timer loop requires Android 9. I can take another look, but chances are probably not good.

**Comment by dubrowgn** [comment]
The variant of `Handler.postDelayed()` I'm using was added in Android 9. I can polyfil it by using `Handler.postAtTime()` and calculating the expiry time myself.

Unfortunately, that only gets us to Android 8 support, since that is the oldest version that supports adaptive icons. I can theoretically polyfil that with static icons for older versions at the expense of APK weight, but at the end of the day I have to draw the line somewhere. For a new app, Android 9 seems like a good trade off at >90% of devices supported according to https://apilevels.com at the time of writing, so this will probably stay as is for the time being, sorry.
